/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Cau1;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import javax.swing.DefaultListModel;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author ASUS
 */
public class cau1b extends javax.swing.JFrame {

    /**
     * Creates new form cau1b
     */
    public cau1b() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtpath = new javax.swing.JTextField();
        ghifile = new javax.swing.JButton();
        docfile = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtnoidung = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Đường dấn đến file:");

        jLabel2.setText("Nội dung file");

        ghifile.setText("Ghi File");
        ghifile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ghifileActionPerformed(evt);
            }
        });

        docfile.setText("Đọc File");
        docfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                docfileActionPerformed(evt);
            }
        });

        jButton3.setText("Thoát");

        txtnoidung.setColumns(20);
        txtnoidung.setRows(5);
        jScrollPane1.setViewportView(txtnoidung);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtpath, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(ghifile)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(docfile)
                                .addGap(53, 53, 53)
                                .addComponent(jButton3)))
                        .addGap(0, 56, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtpath, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ghifile)
                    .addComponent(docfile)
                    .addComponent(jButton3))
                .addGap(68, 68, 68))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void docfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_docfileActionPerformed
     String filePath = txtpath.getText();
     if (filePath.isEmpty()) {
         JOptionPane.showMessageDialog(null, "Vui lòng nhập đường dẫn file!");
         return;
     }

     File file = new File(filePath);

     // Kiểm tra xem file có tồn tại và có phải là file không
     if (!file.exists() || !file.isFile()) {
         JOptionPane.showMessageDialog(null, "File không tồn tại hoặc đường dẫn không đúng!");
         return;
     }

     // Đọc file và hiển thị nội dung mà không in hoa
     try (BufferedReader br = new BufferedReader(new FileReader(file))) {
         StringBuilder content = new StringBuilder();
         String line;
         while ((line = br.readLine()) != null) {
             content.append(line).append("\n"); // Không chuyển thành chữ in hoa
         }
         // Hiển thị nội dung trong JTextArea (txtnoidung)
         txtnoidung.setText(content.toString());
         JOptionPane.showMessageDialog(null, "Đọc file thành công!");
     } catch (IOException e) {
         JOptionPane.showMessageDialog(null, "Lỗi khi đọc file: " + e.getMessage());
     }
    }//GEN-LAST:event_docfileActionPerformed

    private void ghifileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ghifileActionPerformed
    String filePath = txtpath.getText();
    if (filePath.isEmpty()) {
        JOptionPane.showMessageDialog(null, "Vui lòng nhập đường dẫn file!");
        return;
    }
    String content = txtnoidung.getText();
    if (content.isEmpty()) {
        JOptionPane.showMessageDialog(null, "Nội dung trống, không có gì để ghi!");
        return;
    }
    try (BufferedWriter writer = new BufferedWriter(new FileWriter(filePath))) {

        String contentUpperCase = content.toUpperCase();
        writer.write(contentUpperCase);
        JOptionPane.showMessageDialog(null, "Ghi file thành công và nội dung đã được viết hoa!");
    } catch (IOException e) {
        JOptionPane.showMessageDialog(null, "Lỗi khi ghi file: " + e.getMessage());
    }




    }//GEN-LAST:event_ghifileActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(cau1b.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(cau1b.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(cau1b.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(cau1b.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new cau1b().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton docfile;
    private javax.swing.JButton ghifile;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtnoidung;
    private javax.swing.JTextField txtpath;
    // End of variables declaration//GEN-END:variables
}
